# Generated by Django 2.2.5 on 2019-10-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191002_1555'),
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='private',
        ),
        migrations.AddField(
            model_name='chart',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='chart',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
