# Generated by Django 2.2.5 on 2019-10-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20191002_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='author',
            new_name='owner',
        ),
    ]
