# Generated by Django 2.2.5 on 2019-10-04 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_auto_20191003_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='public',
            new_name='privacy',
        ),
    ]
